### ISSUE TITLE
How to compile this on Windows 11?

### ISSUE THREAD

**Issue by Superfly76** [jeremybernstein/modwaveEdit#1]
I really like the looks of this. I'm a non coder musician, and I'd like to use this software to make my own wavetables and to convert other wavetable formats into a format that my modwave can open. It seems that this will do the job. However, I have no idea how to compile code. 

Sorry for the total coder n00b response. 

Thanks!
D

**Comment by jeremybernstein** [comment]
Check out the releases page for [the most recent pre-compiled binaries](https://github.com/jeremybernstein/modwaveEdit/releases/tag/v0.3.0-beta.3).

**Comment by Superfly76** [comment]
Ah,
Thanks so much! I don't know how I missed that. Downloading now. Can't wait
to use it out with my modwave.
Doug McGee

eluviatheband.com
soulflier.com
